{
 "title": "GadukaGang Monitoring",
 "tags": [
  "gadukagang",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Встройка", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Количество GET и POST запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ceil(sum by (method) (rate(gadukagang_django_http_requests_total_by_method_total{instance=\"frontend:8000\"}[$__rate_interval])))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Новые запросы к БД",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(service) (gadukagang_django_db_new_connections_total{instance=\"frontend:8000\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Контроль памяти",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (service) (process_resident_memory_bytes{instance=\"frontend:8000\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Кастом", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Активные пользователи",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gaduka_active_users_total", "legendFormat": "Active users" }
   ]
  },
  {
   "title": "Сообщества",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gaduka_communities_total", "legendFormat": "Communities" }
   ]
  },
  {
   "title": "Активность постов",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 23 },
   "targets": [
    {
     "expr": "ceil(rate(gaduka_posts_total[5m]))",
     "legendFormat": "Posts per minute"
    },
    { "expr": "gaduka_posts_total", "legendFormat": "Total posts" }
   ]
  }
 ]
}