# Generated by Django 5.2.6 on 2025-11-13 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0003_post_dislike_count_post_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topictag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_tags', to='GadukaGang.tag'),
        ),
        migrations.AlterField(
            model_name='topictag',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_tags', to='GadukaGang.topic'),
        ),
    ]
