# Generated by Django 5.2.6 on 2025-11-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0004_alter_topictag_tag_alter_topictag_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]