# Generated by Django 5.2.6 on 2025-11-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0007_practicetopic_practicelevel_userpracticeprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicelevel',
            name='theory_questions',
            field=models.JSONField(default=list),
        ),
    ]
