# Generated by Django 5.2.6 on 2025-11-20 05:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0008_practicelevel_theory_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicelevel',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='practicelevel',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='userpracticeprogress',
            name='level',
        ),
        migrations.AlterUniqueTogether(
            name='userpracticeprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpracticeprogress',
            name='user',
        ),
        migrations.CreateModel(
            name='CertificationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GadukaGang.tag')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_points', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='GadukaGang.certificationsection')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('section', 'level')},
            },
        ),
        migrations.CreateModel(
            name='CodingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('initial_code', models.TextField(default='# Write your code here\n')),
                ('test_cases', models.JSONField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=20)),
                ('is_community_task', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_tasks', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_tasks', to='GadukaGang.certificationstage')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_option_id', models.IntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_questions', to='GadukaGang.certificationstage')),
            ],
        ),
        migrations.CreateModel(
            name='UserCertificationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage_level', models.IntegerField(default=0)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GadukaGang.certificationsection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'section')},
            },
        ),
        migrations.CreateModel(
            name='UserTaskSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('is_passed', models.BooleanField(default=False)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='GadukaGang.codingtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_solutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PracticeTopic',
        ),
        migrations.DeleteModel(
            name='PracticeLevel',
        ),
        migrations.DeleteModel(
            name='UserPracticeProgress',
        ),
    ]
