# Generated by Django 5.2.6 on 2025-11-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0008_practicelevel_theory_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicelevel',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='practicelevel',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='userpracticeprogress',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userpracticeprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='karma',
        ),
        migrations.AlterField(
            model_name='topicview',
            name='view_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='PracticeTopic',
        ),
        migrations.DeleteModel(
            name='PracticeLevel',
        ),
        migrations.DeleteModel(
            name='UserPracticeProgress',
        ),
    ]
