# Generated by Django 5.2.6 on 2025-11-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0009_remove_practicelevel_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationstage',
            name='section',
        ),
        migrations.RemoveField(
            model_name='usercertificationprogress',
            name='section',
        ),
        migrations.AlterUniqueTogether(
            name='certificationstage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='codingtask',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='theoryquestion',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='codingtask',
            name='author',
        ),
        migrations.RemoveField(
            model_name='codingtask',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='usertasksolution',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='usercertificationprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercertificationprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertasksolution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='karma',
        ),
        migrations.AlterField(
            model_name='topicview',
            name='view_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CertificationSection',
        ),
        migrations.DeleteModel(
            name='CertificationStage',
        ),
        migrations.DeleteModel(
            name='TheoryQuestion',
        ),
        migrations.DeleteModel(
            name='CodingTask',
        ),
        migrations.DeleteModel(
            name='UserCertificationProgress',
        ),
        migrations.DeleteModel(
            name='UserTaskSolution',
        ),
    ]
