# Generated by Django 5.2.6 on 2025-11-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0011_community_invite_token_and_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailNotificationSettings',
        ),
    ]
