# Generated by Django 5.2.6 on 2025-11-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0013_course_lesson_courseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='test_input',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='test_output',
            field=models.TextField(blank=True),
        ),
    ]

