# Generated by Django 5.2.6 on 2025-12-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0015_lesson_test_cases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='test_input',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='test_output',
        ),
    ]
