# Generated by Django 5.2.6 on 2025-12-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0016_remove_lesson_test_input_remove_lesson_test_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
