# Generated by Django 5.2.6 on 2026-02-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0022_course_approved_at_course_auto_reject_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlquestion',
            name='question_kind',
            field=models.CharField(choices=[('theory', 'Теоретический'), ('practice', 'Практический')], default='theory', max_length=20),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='is_it',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='practice_mode',
            field=models.CharField(choices=[('code', 'Код'), ('quiz', 'Тест')], default='code', max_length=20),
        ),
    ]
