# Generated by Django 5.2.6 on 2026-02-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0023_controlquestion_question_kind_coursecategory_is_it_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlquestion',
            name='practice_input',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='controlquestion',
            name='practice_output',
            field=models.TextField(blank=True),
        ),
    ]
