# Generated by Django 5.2.6 on 2026-02-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0024_controlquestion_practice_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='practice_task',
            field=models.TextField(blank=True),
        ),
    ]
