# Generated by Django 5.2.6 on 2026-02-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0025_lesson_practice_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlsession',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='control_time_limit_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
