# Generated by Codex on 2026-02-13

import uuid
from django.db import migrations


def fill_verification_codes(apps, schema_editor):
    UserCertificate = apps.get_model('GadukaGang', 'UserCertificate')
    for cert in UserCertificate.objects.filter(verification_code__isnull=True):
        code = uuid.uuid4().hex
        while UserCertificate.objects.filter(verification_code=code).exists():
            code = uuid.uuid4().hex
        cert.verification_code = code
        cert.save(update_fields=['verification_code'])

    for cert in UserCertificate.objects.filter(verification_code=''):
        code = uuid.uuid4().hex
        while UserCertificate.objects.filter(verification_code=code).exists():
            code = uuid.uuid4().hex
        cert.verification_code = code
        cert.save(update_fields=['verification_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0027_usercertificate_verification_code_coursefavorite'),
    ]

    operations = [
        migrations.RunPython(fill_verification_codes, migrations.RunPython.noop),
    ]
