# Generated by Codex on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GadukaGang', '0028_backfill_usercertificate_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertificate',
            name='verification_code',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
